#----------------------------------------------------------------
# A complete control mode is an 8 bits flag 
# (4bits control mode + 2 yaw mode bits + 2 reference frame bits)
#
# ------------- mode codification (4 bits) ----------------------
#
# unset             = 0 = 0b0000
# hover             = 1 = 0b0001
# acro              = 2 = 0b0010
# attitude          = 3 = 0b0011
# speed             = 4 = 0b0100
# speed_in_a_plane  = 5 = 0b0101
# position          = 6 = 0b0110
# trajectory        = 7 = 0b0111
#
#-------------- yaw codification --------------------------------
# 
# angle             = 0 = 0b00
# speed             = 1 = 0b01
# 
# frame codification
# 
# local_frame_flu   = 0 = 0b00
# global_frame_enu  = 1 = 0b01
# global_frame_lla  = 2 = 0b10
# 
#-----------------------------------------------------------------

/**:
  ros__parameters:
    available_modes:
      # Betaflight MSP supports limited control modes for compatibility
      - 0  # 0b00000000 # UNSET
      - 16 # 0b00010000 # HOVER
      - 49 # 0b00110001 # ATTITUDE with yaw ANGLE ( r,p,y , Thrust) 
      - 53 # 0b00110101 # ATTITUDE with yaw SPEED ( r,p, dy , Thrust) 
      - 68 # 0b01000100 # SPEED with yaw SPEED in the LOCAL_FLU_FRAME
      - 69 # 0b01000101 # SPEED with yaw SPEED in the GLOBAL_ENU_FRAME
