name: Feature Request
description: Tell us about your great new idea.
title: "[as2_pkg]: "
labels: ["enhancement"]
assignees:
  - octocat
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Tell us about your great new idea.
    validations:
      required: true
  - type: textarea
    id: implementation-considerations
    attributes:
      label: Implementation Considerations
      description: Please add here any important implementation consideration.
