name: Build External Platforms

on:
  pull_request:
    types: [review_requested, ready_for_review]
    branches:
      - main

jobs:
  wait-for-build:
    name: Wait for build
    runs-on: ubuntu-latest
    if : github.event_name != 'workflow_dispatch'
    steps:
      - name: Wait for check to pass
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.ref }}
          check-name: 'Build and test humble'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

  build-platforms:
    runs-on: ubuntu-latest
    needs: wait-for-build
    strategy:
      matrix:
        repos: [as2_platform_crazyflie, as2_platform_tello]
    steps:
      - name: Dispatch an action and get the run ID
        uses: codex-/return-dispatch@v1
        id: return_dispatch
        with:
          token: ${{ secrets.TOKEN }}
          ref: main
          repo: ${{ matrix.repos }}
          owner: aerostack2
          workflow: build_humble.yaml
          workflow_inputs: "{ \"target_branch\": \"${{ github.ref_name }}\" }"
      - name: Await Run ID ${{ steps.return_dispatch.outputs.run_id }}
        uses: Codex-/await-remote-run@v1.0.0
        with:
          token: ${{ github.token }}
          repo: ${{ matrix.repos }}
          owner: aerostack2
          run_id: ${{ steps.return_dispatch.outputs.run_id }}
          run_timeout_seconds: 3600 # Optional
          poll_interval_ms: 5000 # Optional

