name: Build External Platforms

on:
  pull_request:
    types: [review_requested, ready_for_review]
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch an action and get the run ID
        uses: codex-/return-dispatch@v1
        id: return_dispatch
        with:
          token: ${{ secrets.TOKEN }}
          repo: as2_platform_crazyflie
          owner: aerostack2
          workflow: build_humble.yaml
      - name: Await Run ID ${{ steps.return_dispatch.outputs.run_id }}
        uses: Codex-/await-remote-run@v1.0.0
        with:
          token: ${{ github.token }}
          repo: as2_platform_crazyflie
          owner: aerostack2
          run_id: ${{ steps.return_dispatch.outputs.run_id }}
